server:
  port: 8080


spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/demo_jpa}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    password: ${DBMS_PASSWORD:root}
    username: ${DBMS_USERNAME:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true